# Generated by Django 4.1 on 2022-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_cateogry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cateogry",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category"),
        ),
    ]
