# Generated by Django 4.1 on 2022-10-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_cateogry_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cateogry",
            new_name="Category",
        ),
    ]
